'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Comun.ProveedoresFletes.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE dbo.Cliente
        '''SET
        '''	[Nombre] = &apos;{Nombre}&apos;,
        '''	[DiasDePago] = {DiasDePago},
        '''	[Temperatura] = {Temperatura},
        '''	[Flete] = {Flete},
        '''	[Tipo] = &apos;{Tipo}&apos;,
        '''	[Porcentaje] = {Porcentaje},
        '''	[Absoluto] = &apos;{Absoluto}&apos;,
        '''	[ProveedorId] = {ProveedorId}
        '''WHERE
        '''	[Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property ActualizarCliente() As String
            Get
                Return ResourceManager.GetString("ActualizarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE dbo.Contacto
        '''SET
        '''	[Nombre] = &apos;{Nombre}&apos;,
        '''	[Departamento] = &apos;{Departamento}&apos;,
        '''	[EMail] = &apos;{EMail}&apos;,
        '''	[Telefono] = &apos;{Telefono}&apos;,
        '''	[ProveedorId] = {ProveedorId}
        '''WHERE
        '''	[Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property ActualizarContacto() As String
            Get
                Return ResourceManager.GetString("ActualizarContacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE dbo.Flete
        '''SET
        '''	[Negocio] = &apos;{Negocio}&apos;,
        '''	[CostoTotal] = {CostoTotal},
        '''	[ProveedorId] = {ProveedorId}
        '''WHERE
        '''	[Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property ActualizarFlete() As String
            Get
                Return ResourceManager.GetString("ActualizarFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE dbo.Proveedor
        '''SET
        '''	[Nombre] = &apos;{Nombre}&apos;,
        '''	[Direccion] = &apos;{Direccion}&apos;,
        '''	[RefProveedor] = {RefProveedor}
        '''WHERE
        '''	[Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property ActualizarProveedor() As String
            Get
                Return ResourceManager.GetString("ActualizarProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.FleteProducto
        '''    ([ProductoId],[FleteId],[Costo])
        '''VALUES
        '''    ({ProductoId},{FleteId},{Costo}).
        '''</summary>
        Friend ReadOnly Property AnadirProductosDelFlete() As String
            Get
                Return ResourceManager.GetString("AnadirProductosDelFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.Cliente
        '''	([Nombre],[DiasDePago],[Temperatura],[Flete],[Tipo],[Porcentaje],[Absoluto],[ProveedorId])
        '''VALUES
        '''	(&apos;{Nombre}&apos;,{DiasDePago},{Temperatura},{Flete},&apos;{Tipo}&apos;,{Porcentaje},&apos;{Absoluto}&apos;,{ProveedorId}).
        '''</summary>
        Friend ReadOnly Property CrearCliente() As String
            Get
                Return ResourceManager.GetString("CrearCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXECUTE CrearCliente
        '''    &apos;{Nombre}&apos;,
        '''    {DiasDePago},
        '''    {Temperatura},
        '''    {Flete},
        '''    &apos;{Tipo}&apos;,
        '''    {Porcentaje},
        '''    &apos;{Absoluto}&apos;,
        '''    {ProveedorId}.
        '''</summary>
        Friend ReadOnly Property CrearClienteProcedimento() As String
            Get
                Return ResourceManager.GetString("CrearClienteProcedimento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.Contacto
        '''	([Nombre],[Departamento],[EMail],[Telefono],[ProveedorId])
        '''VALUES
        '''	(&apos;{Nombre}&apos;,&apos;{Departamento}&apos;,&apos;{EMail}&apos;,&apos;{Telefono}&apos;,{ProveedorId}).
        '''</summary>
        Friend ReadOnly Property CrearContacto() As String
            Get
                Return ResourceManager.GetString("CrearContacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.Flete
        '''	([Negocio],[CostoTotal],[ProveedorId])
        '''VALUES
        '''	(&apos;{Negocio}&apos;,{CostoTotal},{ProveedorId}).
        '''</summary>
        Friend ReadOnly Property CrearFlete() As String
            Get
                Return ResourceManager.GetString("CrearFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.Proveedor
        '''	([Nombre],[Direccion],[RefProveedor])
        '''VALUES
        '''	(&apos;{Nombre}&apos;,&apos;{Direccion}&apos;,{RefProveedor}).
        '''</summary>
        Friend ReadOnly Property CrearProveedor() As String
            Get
                Return ResourceManager.GetString("CrearProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM dbo.Cliente
        '''WHERE [Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property EliminarCliente() As String
            Get
                Return ResourceManager.GetString("EliminarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM dbo.Contacto
        '''WHERE [Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property EliminarContacto() As String
            Get
                Return ResourceManager.GetString("EliminarContacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM dbo.Flete
        '''WHERE [Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property EliminarFlete() As String
            Get
                Return ResourceManager.GetString("EliminarFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM dbo.FleteProducto
        '''WHERE [FleteId] = {FleteId}.
        '''</summary>
        Friend ReadOnly Property EliminarProductosDelFlete() As String
            Get
                Return ResourceManager.GetString("EliminarProductosDelFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM dbo.Proveedor
        '''WHERE [Id] = {Id}.
        '''</summary>
        Friend ReadOnly Property EliminarProveedor() As String
            Get
                Return ResourceManager.GetString("EliminarProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Cliente
        '''	WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ObtenerCliente() As String
            Get
                Return ResourceManager.GetString("ObtenerCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Cliente.
        '''</summary>
        Friend ReadOnly Property ObtenerClientes() As String
            Get
                Return ResourceManager.GetString("ObtenerClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Contacto
        '''	WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ObtenerContacto() As String
            Get
                Return ResourceManager.GetString("ObtenerContacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Contacto.
        '''</summary>
        Friend ReadOnly Property ObtenerContactos() As String
            Get
                Return ResourceManager.GetString("ObtenerContactos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Flete
        '''	WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ObtenerFlete() As String
            Get
                Return ResourceManager.GetString("ObtenerFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Flete.
        '''</summary>
        Friend ReadOnly Property ObtenerFletes() As String
            Get
                Return ResourceManager.GetString("ObtenerFletes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Producto
        '''	WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ObtenerProducto() As String
            Get
                Return ResourceManager.GetString("ObtenerProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Producto.
        '''</summary>
        Friend ReadOnly Property ObtenerProductos() As String
            Get
                Return ResourceManager.GetString("ObtenerProductos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''	P.Id,
        '''	P.Descripcion,
        '''	FP.Costo AS CostoDelFlete
        '''FROM
        '''	dbo.FleteProducto FP
        '''	INNER JOIN dbo.Producto P ON P.Id = FP.ProductoId
        '''WHERE FP.FleteId = {FleteId}.
        '''</summary>
        Friend ReadOnly Property ObtenerProductosDelFlete() As String
            Get
                Return ResourceManager.GetString("ObtenerProductosDelFlete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Proveedor
        '''	WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ObtenerProveedor() As String
            Get
                Return ResourceManager.GetString("ObtenerProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''	FROM dbo.Proveedor.
        '''</summary>
        Friend ReadOnly Property ObtenerProveedores() As String
            Get
                Return ResourceManager.GetString("ObtenerProveedores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''TOP 1 *
        '''FROM dbo.Flete
        '''ORDER BY Id DESC.
        '''</summary>
        Friend ReadOnly Property ObtenerUltimoFleteIncluido() As String
            Get
                Return ResourceManager.GetString("ObtenerUltimoFleteIncluido", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
